source "https://supermarket.chef.io"

metadata

cookbook "kea", github: "randomcoww/chef-kea", branch: "attr"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
