name             'kea-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kea-app'
long_description 'Installs/Configures kea-app'
version          '0.1.0'
depends          'environment'
