name             'kube_master'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kube_master'
long_description 'Installs/Configures kube_master'
version          '0.1.0'
depends          'environment'
depends          'kubernetes'
depends          'dbag'
depends          'node_data'
depends          'systemd_resource'
