name             'system_update'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures system_update'
long_description 'Installs/Configures system_update'
version          '0.1.0'
