name             'docker_overlay'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures docker_overlay'
long_description 'Installs/Configures docker_overlay'
version          '0.1.0'
depends          'environment'
depends          'dbag'
depends          'node_data'
depends          'systemd_resource'
