# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "qemu", github: "randomcoww/chef-qemu"
