source "https://supermarket.chef.io"

metadata

cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
cookbook "transmission", github: "randomcoww/chef-transmission"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
