source "https://supermarket.chef.io"

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
cookbook "knot", github: "randomcoww/chef-knot"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "mysql_credentials", github: "randomcoww/chef-apps", rel: "mysql_credentials"
cookbook "mysql_cluster", github: "randomcoww/chef-mysql_cluster"
