name             'knot-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures knot-app'
long_description 'Installs/Configures knot-app'
version          '0.1.0'
depends          'environment'
depends          'dbag'
depends          'knot'
depends          'systemd_resource'
