name             'ddclient-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ddclient-app'
long_description 'Installs/Configures ddclient-app'
version          '0.1.0'
depends          'environment'
depends          'ddclient'
depends          'dbag'
