source "https://supermarket.chef.io"

metadata

cookbook "nsd", github: "randomcoww/chef-nsd"
cookbook "nsd_resource", github: "randomcoww/chef-nsd_resource"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
