name             'nsd-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nsd-app'
long_description 'Installs/Configures nsd-app'
version          '0.1.0'
depends          'environment'
depends          'mysql_credentials'
depends          'mysql_cluster'
depends          'nsd'
depends          'dbag'
depends          'nsd_resource'
