name             'kubelet-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kubelet-app'
long_description 'Installs/Configures kubelet-app'
version          '0.1.0'
depends          'kubernetes-app'
