# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-deploys", rel: "environment"
cookbook "haproxy_resource", github: "randomcoww/chef-haproxy_resource"
cookbook "openssl_cert", github: "randomcoww/chef-openssl_cert"
cookbook "dbag", github: "randomcoww/chef-dbag"
