name             'openvpn-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures openvpn-pod'
long_description 'Installs/Configures openvpn-pod'
version          '0.1.0'
depends          'dbag'
depends          'environment'
depends          'openvpn'
depends          'openssl_cert'
depends          'systemd_resource'
