name             'openvpn_client-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures openvpn_client-app'
long_description 'Installs/Configures openvpn_client-app'
version          '0.1.0'
depends          'environment'
depends          'openvpn'
depends          'dbag'
