node.default['kube']['images']['mysql_cluster_mysqld'] = "randomcoww/k8s-mysql_cluster_mysqld:latest"
node.default['kube']['images']['mysql_cluster_ndbd'] = "randomcoww/k8s-mysql_cluster_ndbd:latest"
node.default['kube']['images']['mysql_cluster_ndb_mgmd'] = "randomcoww/k8s-mysql_cluster_ndb_mgmd:latest"
node.default['kube']['images']['kea_dhcp4'] = "randomcoww/k8s-kea:latest"
node.default['kube']['images']['kea_dhcp_ddns'] = "randomcoww/k8s-kea:latest"
node.default['kube']['images']['haproxy'] = "randomcoww/k8s-haproxy:latest"
