source "https://supermarket.chef.io"

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "node_data", github: "randomcoww/chef-node_data"
