name             'environment'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures environment'
long_description 'Installs/Configures environment'
version          '0.1.0'
