name             'kubernetes-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kubernetes-app'
long_description 'Installs/Configures kubernetes-app'
version          '0.1.0'
depends          'environment'
depends          'kubernetes'
depends          'dbag'
depends          'node_data'
depends          'systemd_resource'
depends          'docker'
