# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "dns_zone", github: "randomcoww/chef-dns_zone"
cookbook "keepalived_resource", github: "randomcoww/chef-keepalived_resource"
cookbook "nsd_resource", github: "randomcoww/chef-nsd_resource"
cookbook "knot", github: "randomcoww/chef-knot"
cookbook "openvpn", github: "randomcoww/chef-openvpn"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
cookbook "openssl_cert", github: "randomcoww/chef-openssl_cert"
