name 'dns-manifest'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures dns-manifest'
long_description 'Installs/Configures dns-manifest'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
depends          'dbag'
depends          'environment'
depends          'dns_zone'
depends          'keepalived_resource'
depends          'nsd_resource'
depends          'knot'
depends          'openvpn'
depends          'openssl_cert'
depends          'systemd_resource'
