name             'unbound-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures unbound-app'
long_description 'Installs/Configures unbound-app'
version          '0.1.0'
depends          'environment'
depends          'unbound'
depends          'dbag'
depends          'nsd_resource'
