source "https://supermarket.chef.io"

metadata

cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "openvpn", github: "randomcoww/chef-openvpn"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
