name             'sshd-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sshd-app'
long_description 'Installs/Configures sshd-app'
version          '0.1.0'
depends          'environment'
depends          'sshd'
