name             'etcd-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures etcd-app'
long_description 'Installs/Configures etcd-app'
version          '0.1.0'
depends          'environment'
depends          'etcd'
depends          'dbag'
