source "https://supermarket.chef.io"

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
cookbook "keepalived_resource", github: "randomcoww/chef-keepalived_resource"
