name             'gluster-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures gluster-pod'
long_description 'Installs/Configures gluster-pod'
version          '0.1.0'
depends          'dbag'
depends          'environment'
depends          'systemd_resource'
depends          'keepalived_resource'
