# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-deploys", rel: "environment"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
