name             'register_resource'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures register_resource'
long_description 'Installs/Configures register_resource'
version          '0.1.0'
depends          'dbag'
depends          'environment_resource'
