name             'keepalived-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures keepalived-pod'
long_description 'Installs/Configures keepalived-pod'
version          '0.1.0'
depends          'keepalived_resource'
depends          'environment'
depends          'dbag'
