name             'mysql_cluster-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql_cluster-app'
long_description 'Installs/Configures mysql_cluster-app'
version          '0.1.0'
depends          'environment'
depends          'mysql_credentials'
depends          'mysql_cluster'
depends          'dbag'
