# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-deploys", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "ddclient", github: "randomcoww/chef-ddclient"
