name             'dns-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dns-pod'
long_description 'Installs/Configures dns-pod'
version          '0.1.0'
depends          'dbag'
depends          'environment'
depends          'dns_zone'
depends          'keepalived_resource'
depends          'nsd_resource'
depends          'knot'
depends          'openvpn'
depends          'openssl_cert'
depends          'systemd_resource'
