name             'ddclient-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ddclient-pod'
long_description 'Installs/Configures ddclient-pod'
version          '0.1.0'
depends          'environment'
depends          'dbag'
depends          'ddclient'
