source "https://supermarket.chef.io"

metadata

cookbook "mysql-cluster", github: "randomcoww/chef-mysql-cluster"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
