name             'mysql-cluster-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql-cluster-app'
long_description 'Installs/Configures mysql-cluster-app'
version          '0.1.0'
depends          'environment'
depends          'mysql-cluster'
