node['qemu']['gateway']['hosts'].each do |host, config|

  host_config = node['environment_v2']['host'][host]

  mac_wan = host_config['mac_wan']
  memory = host_config['memory']
  vcpu = host_config['vcpu']

  networks = [
    {
      "#attributes"=>{
        "type"=>"direct",
        "trustGuestRxFilters"=>"yes"
      },
      "source"=>{
        "#attributes"=>{
          "dev"=>node['environment_v2']['node_host']['if_lan'],
          "mode"=>"bridge"
        }
      },
      "model"=>{
        "#attributes"=>{
          "type"=>"virtio-net"
        }
      }
    },
    {
      "#attributes"=>{
        "type"=>"direct",
        "trustGuestRxFilters"=>"yes"
      },
      "source"=>{
        "#attributes"=>{
          "dev"=>node['environment_v2']['node_host']['if_wan'],
          "mode"=>"bridge"
        }
      },
      "mac"=>{
        "#attributes"=>{
          "address"=>mac_wan
        }
      },
      "model"=>{
        "#attributes"=>{
          "type"=>"virtio-net"
        }
      }
    }
  ]

  cidr = node['environment_v2']['subnet']['lan'].split('/').last.to_i
  static_ip_append = [
    host_config['ip_lan'],
    nil,
    nil,
    IPAddr.new('255.255.255.255').mask(cidr).to_s,
    nil,
    host_config['if_lan'],
    'none'
  ].join(':')

  node.default['qemu']['configs'][host] = LibvirtConfig::ConfigGenerator.generate_from_hash({
    "domain"=>{
      "#attributes"=>{
        "type"=>"kvm"
      },
      "name"=>host,
      "memory"=>{
        "#attributes"=>{
          "unit"=>"MiB"
        },
        "#text"=>memory
      },
      "currentMemory"=>{
        "#attributes"=>{
          "unit"=>"MiB"
        },
        "#text"=>memory
      },
      "vcpu"=>{
        "#attributes"=>{
          "placement"=>"static"
        },
        "#text"=>vcpu
      },
      "iothreads"=>"1",
      "iothreadids"=>{
        "iothread"=>{
          "#attributes"=>{
            "id"=>"1"
          }
        }
      },
      "os"=>{
        "type"=>{
          "#attributes"=>{
            "arch"=>"x86_64",
            "machine"=>"pc"
          },
          "#text"=>"hvm"
        },
        "kernel"=>{
          "#text"=>node['qemu']['pxe_kernel_path']
        },
        "initrd"=>{
          "#text"=>node['qemu']['pxe_initrd_path']
        },
        "cmdline"=>{
          "#text"=>[
            "coreos.first_boot=1",
            "console=ttyS0",
            "coreos.config.url=http://#{node['environment_v2']['node_host']['ip_lan']}:#{node['environment_v2']['service']['manifest_server']['bind']}/ignition/#{host}",
            "ip=#{static_ip_append}"
          ].join(' '),
        },
        "boot"=>{
          "#attributes"=>{
            "dev"=>"hd"
          }
        }
      },
      "features"=>{
        "acpi"=>"",
        "apic"=>"",
        "pae"=>""
      },
      "cpu"=>{
        "#attributes"=>{
          "mode"=>"host-passthrough"
        },
        "topology"=>{
          "#attributes"=>{
            "sockets"=>"1",
            "cores"=>vcpu,
            "threads"=>"1"
          }
        }
      },
      "clock"=>{
        "#attributes"=>{
          "offset"=>"utc"
        }
      },
      "on_poweroff"=>"destroy",
      "on_reboot"=>"restart",
      "on_crash"=>"restart",
      "devices"=>{
        "emulator"=>"/usr/bin/qemu-system-x86_64",
        "controller"=>[
          {
            "#attributes"=>{
              "type"=>"usb",
              "index"=>"0",
              "model"=>"none"
            }
          },
          {
            "#attributes"=>{
              "type"=>"pci",
              "index"=>"0",
              "model"=>"pci-root"
            }
          }
        ],
        "interface"=>networks,
        "serial"=>{
          "#attributes"=>{
            "type"=>"pty"
          },
          "target"=>{
            "#attributes"=>{
              "port"=>"0"
            }
          }
        },
        "console"=>{
          "#attributes"=>{
            "type"=>"pty"
          },
          "target"=>{
            "#attributes"=>{
              "type"=>"serial",
              "port"=>"0"
            }
          }
        },
        "input"=>[
          {
            "#attributes"=>{
              "type"=>"mouse",
              "bus"=>"ps2"
            }
          },
          {
            "#attributes"=>{
              "type"=>"keyboard",
              "bus"=>"ps2"
            }
          }
        ],
        "memballoon"=>{
          "#attributes"=>{
            "model"=>"virtio"
          }
        }
      }
    }
  })

end
