# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "ignition", github: "randomcoww/chef-ignition"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
