# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "environment", github: "randomcoww/chef-deploys", rel: "environment"
cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "haproxy_resource", github: "randomcoww/chef-haproxy_resource"
cookbook "keepalived_resource", github: "randomcoww/chef-keepalived_resource"
