name             'haproxy-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures haproxy-app'
long_description 'Installs/Configures haproxy-app'
version          '0.1.0'
depends          'environment'
depends          'haproxy'
depends          'mysql_cluster'
depends          'dbag'
