source "https://supermarket.chef.io"

metadata

cookbook "cassandra", github: "randomcoww/chef-cassandra"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "node_data", github: "randomcoww/chef-node_data"
cookbook "docker"
