name             'cql-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cql-app'
long_description 'Installs/Configures cql-app'
version          '0.1.0'
depends          'environment'
depends          'cassandra'
depends          'node_data'
