source "https://supermarket.chef.io"

metadata

cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "glusterfs", github: "randomcoww/chef-glusterfs"
cookbook "node_data", github: "randomcoww/chef-node_data"
cookbook "dbag", github: "randomcoww/chef-dbag"
