source "https://supermarket.chef.io"

metadata

cookbook "qemu", github: "randomcoww/chef-qemu"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
cookbook "systemd_resource", github: "randomcoww/chef-systemd_resource"
