name             'qemu-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures qemu-app'
long_description 'Installs/Configures qemu-app'
version          '0.1.0'
depends          'environment'
depends          'qemu'
