name             'environment_vm2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures environment_vm2'
long_description 'Installs/Configures environment_vm2'
version          '0.1.0'
