name             'kea-pod'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kea-pod'
long_description 'Installs/Configures kea-pod'
version          '0.1.0'
depends          'kea'
depends          'mysql_cluster'
depends          'mysql_credentials'
depends          'environment'
depends          'dbag'
