name             'glusterfs-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures glusterfs-app'
long_description 'Installs/Configures glusterfs-app'
version          '0.1.0'
depends          'environment'
depends          'glusterfs'
depends          'node_data'
depends          'dbag'
