source "https://supermarket.chef.io"

metadata

cookbook "dbag", github: "randomcoww/chef-dbag"
cookbook "ddclient", github: "randomcoww/chef-ddclient"
cookbook "environment", github: "randomcoww/chef-apps", rel: "environment"
